### ISSUE TITLE
Beta No More?

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#112]
@ajhodges @austin9350 

If the phones on the trolley work like we want and expect to are we ready to take the apps out of beta?

**Comment by ajhodges** [comment]
It definitely makes me more comfortable. I have noticed a couple UI glitches that need fixing and then there's the list of to-do features in https://github.com/codeforgreenville/trolley-tracker-android-client/issues 

Maybe you or @jeremywight could go through those issues and make 'milestones' and tag the issues with milestones in order of priority?

I think most of those issues wouldn't take long to fix, I've just lacked motivation to get it done with our beacon being so inconsistent.

**Comment by agautsc** [comment]
@ajhodges 

I added to the milestone to two items. The big one for me is the zooming issue. That one hurts the user experience. The other one is the more detail on stops and that's really a "nice to have" more than a "need to have"

Others feel free to share more thoughts where needed.
:trolleybus:

**Comment by greenlinktransit** [comment]
![ios screenshot 1](https://cloud.githubusercontent.com/assets/14838562/11542949/0678a8dc-9908-11e5-8d7f-63a1c89a9feb.jpg)
![ios screenshot 2](https://cloud.githubusercontent.com/assets/14838562/11542948/06782c2c-9908-11e5-806f-9ec8307d517a.jpg)
![ios screenshot 3](https://cloud.githubusercontent.com/assets/14838562/11542950/0679ae30-9908-11e5-930d-45523b329607.jpg)

**Comment by greenlinktransit** [comment]
I just tried opening the Trolley Tracker app and the screenshots above show what I was able to see.  Apologies for the giant screenshots.

Does everyone need to remember their TestFlight invitation code to update it?

**Comment by austin9350** [comment]
I just reset the beta build, I think you should have received an email saying there is a new version available. It's not really a new version, but for some reason it was showing expired even there it should have another 4 weeks left before it expired.
Apple has been updating some of the features of their beta testing service and there have been a few.... hiccups along the way.
You shouldn't have to reenter an invite code, hopefully you should just be able to open the TestFlight app and install the latest version, definitely let me know if that's not the case and I'll do whatever I can to troubleshoot.

**Comment by austin9350** [comment]
@agautsc I'm fine with moving the iOS app out of beta.

**Comment by greenlinktransit** [comment]
@austin9350 thanks -- I downloaded the update and I regained access to the app
