### ISSUE TITLE
Beta Tester Email

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#113]
Send an email to all Beta testers letting them know about the update to the beacon.

**Comment by agautsc** [comment]
Sent. 91 / 181 opens. 23 click most on YeahThatTrolley.com 7 new Beta signups. No support emails or new ideas submitted.

**Comment by jeremywight** [comment]
@agautsch This person requested to get on the iPhone Beta test group and
didn't receive an invite: soconne@g.clemson.edu

Not sure why. Can we get him added.

**Comment by agautsc** [comment]
@austin9350 sends iOS emails. He can help.
