### ISSUE TITLE
Trolley 5 Didn't Come Online Thursday

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#115]
Thursday (12/3) trolley 5 never showed up online. 

Here's @bikeoid comment from the "New Device" thread
https://github.com/codeforgreenville/trolley-tracker/issues/105#issuecomment-161868657
Trolley 5 was last seen at city hall, so it's never obtained a GPS fix from the trolley.

And @greenlinktransit 's response
https://github.com/codeforgreenville/trolley-tracker/issues/105#issuecomment-161972819
I've alerted OPS about the new devices and have asked them to keep an eye on the tracker over the next couple weeks to see if there's a certain trolley that's working better than the other. I've also asked them to give me a heads up if a trolley ever goes out of service, is late, etc. I know that the trolley schedule is going to be weird tomorrow with the parade -- I believe we're decorating both trolleys in the morning, so we probably won't have anything to look at until after the parade is over.

Lastly, we have a new General Manager of OPS starting with us on Monday. He's young and understands technology very well. Once he gets settled in, I'd like to set up a short meeting so we can brief him on the Trolley Tracker and how he can assist.

Thanks again for everyone's hard work on this.

**Comment by tkenney-gvl** [comment]
Since 5 is having issues, I'll comment here so we can keep date and time logs. As of this writing Trolley 1 (#5) just passed by city hall not 5-10 minutes ago and I tracked it. It came online shortly after 11:00 when the Friday lunch run was scheduled. I'll be tracking it off and on throughout the lunch run today.

**Comment by tkenney-gvl** [comment]
Just passed city hall again right now and it's accurate still. I'll wait till the end of the shift now and see if it stays on beyond where it's supposed to.

**Comment by agautsc** [comment]
Good news. I am only seeing one trolley on the map. @greenlinktransit does only one trolley run during lunch?

**Comment by tkenney-gvl** [comment]
I spoke with Grant this morning and he said that only 1 trolley runs during the lunch time on Friday, so yep :)

**Comment by ajhodges** [comment]
Since 5 seems to be working fine today (knock on wood) can we confirm that it was even running last night? 6 seemed to be running a limited route which makes me wonder if 5 was even in service.

**Comment by greenlinktransit** [comment]
Just intercepted the Trolley on route.  Trolley 5 aka Trolley #2 on the app currently has the phone on the dash, not the overhead bin.  Seems to be working like a charm.

**Comment by greenlinktransit** [comment]
I was re-reading the thread and realized that there's some confusion about the trolley names.  Just so we're clear, here are the names and configurations:

Trolley #1 (app) = Trolley 6 & has the phone installed in the overhead bin
Trolley #2 (app) = Trolley 5 & has the phone installed on the dash

I took a screenshot of my phone last night at 9:30PM and it only shows Trolley #1 in service.  Not sure if that was a fluke or not....

**Comment by ajhodges** [comment]
I wouldn't rely on the numbering in the apps, it is arbitrary (you will never see a trolley 2 without a trolley 1). You can see which trolley is actually running by going to http://api.yeahthattrolley.com/DbVisualizer/

So last night Trolley 1 was actually trolley 6 and today Trolley 1 is trolley 5.

We could change the numbering of the trolleys in the apps if we need to..

**Comment by greenlinktransit** [comment]
Oh wow, never knew that.  Thanks for sharing.  I guess the app identifier doesn't matter as long as everyone refers to them as Trolley 5 or 6 (which you guys seem to be doing anyway).

Sorry if I confused anyone.

**Comment by ajhodges** [comment]
And I might be confused too because you said Trolley 5 is showing up as 2 in the app today. I'm guessing you are using the iOS app, and I'm actually not sure how the trolleys are numbered in that app. So maybe I need to collaborate with @austin9350 and come up with a convention for that so we're at least consistent across apps.

Either way, the DbVisualizer is going to be the most accurate reference since it shows our numbering, the license plate numbering, and Greenlink's numbering thanks to Tristan's configuration :)

**Comment by tkenney-gvl** [comment]
Ok, so after the trolley ended its run for the day it still showed online. Grant went over there to check it out and found the phone on, but the charging indicator was showing that the phone was running on battery. We tested a lot of things, going through having it completely off (manually) and cranking the trolley, which resulted in the phone turning on. After the boot, we turned the trolley off, but the phone stayed on. He took it out of the cradle so it wouldn't have anything connected to it and it was still on. I had him double-check the trolley app settings, and both checkboxes were checked (background testing and auto-off). We did run into some phone glitches where the phone rebooted 2 times after we cranked the trolley and then before the Nexus was fully booted turned the trolley back off again, but other than that, the power stuff seems to be working as expected with exception of it not wanting to turn off when no power is supplied. I'm not sure if you can get debug info from the Tracker app itself, but it looks like it's either not executing the reboot -p option or something in the system is overriding it (for that phone). We'll have to see about number 6 tonight and see if we have something similar.

**Comment by bikeoid** [comment]
Trolley 5 was the only one seen tonight, and was working well until it dropped of the map at about 9:00.

**Comment by ajhodges** [comment]
I'm at the parade, trolleys just drove by noma. Not showing up on the app :(

Are they using the old trolleys in the parade? I see 6 is still hanging out
in the west end... So it can't have been 6. Unless they took the phone out?

**Comment by greenlinktransit** [comment]
Last I heard they were going to use Trolley 5 and 6 in the parade. The old trolley doesn't run anymore. And we shouldn't have taken the devices off...

**Comment by ajhodges** [comment]
Very strange. When I just looked at the app trolley 6 was by the peace
center and then it superspeeded to county square in about 30 secs. Looks
like we have other issues unless I've had one too many.

**Comment by ajhodges** [comment]
And I just watched it zip back up main street in about a minute.

**Comment by bikeoid** [comment]
Last night's outage on Trolley 5 started at 9:00 and lasted until 11:08.  It was probably a maintenance ignition cycle that restarted it finally.    Trolley 6 started for a short period of time after 11:00PM also; probably normal maintenance.   There was no superspeed behavior that time.

Thought: since the phone is dash mounted on Trolley 5, could it have been that the driver needed to charge their cell phone at 9:00?   

  That doesn't explain any of Trolley 6 behavior tonight though.

**Comment by greenlinktransit** [comment]
Wouldn't the tracker still work even if it was unplugged from its power source (so long as the phone doesn't run out of battery)? I took the Nexus out of the mount yesterday and it was showing on the tracker...

**Comment by ajhodges** [comment]
I pushed an update to the app the other day that makes the phone turn off
when it is unplugged (so we don't need the drivers to turn it on/off). So
the tracker won't run when the device is unplugged anymore. From the
behavior tonight though, it looks like we have some more debugging to do...
very strange.

**Comment by agautsc** [comment]
Closing issue. Phones seem to be behaving correctly. Will create a new one if issues arise again.
