### ISSUE TITLE
Wednesday Meetup

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#117]
Hodges suggested we meetup https://github.com/codeforgreenville/trolley-tracker/issues/116#issuecomment-164427132 one more time before we take this bad boy out of Beta.

:hand: If you're able and interested this Wednesday.

**Comment by ajhodges** [comment]
:hand:

**Comment by greenlinktransit** [comment]
:hand: (before 2PM)

**Comment by jeremywight** [comment]
If before 2pm I can do if it's in the morning 8 or 830

**Comment by bikeoid** [comment]
:hand: I think I can make it

**Comment by agautsc** [comment]
I don't think @ajhodges could do morning time. How many folks could do the evening. 615pm time frame? @austin9350 could you attend?

**Comment by bikeoid** [comment]
I can make evening or morning.

**Comment by greenlinktransit** [comment]
My schedule for tomorrow was just re-shuffled.  I'll be in a meeting all morning and I have a 3:30pm meeting in Clemson.  I should be back well before 6:15pm...

**Comment by agautsc** [comment]
Let's do 630pm at Coffee Underground

**Comment by austin9350** [comment]
6:30 at coffee underground works for me.

**Comment by ajhodges** [comment]
:coffee: see yall there.

**Comment by jeremywight** [comment]
I've got a ship deadline tomorrow but I'm going to do my best to get down
there.

Jeremy
