### ISSUE TITLE
Testing Dec 17 to Dec 20

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#118]
I didn't check last night (Thursday) did things go off without a hitch?

**Comment by greenlinktransit** [comment]
I checked it twice and both times it was working.

**Comment by ajhodges** [comment]
Same here. And I saw a trolley on this morning, and it looks like lunchlink
is warming up right now!

Loving this auto-off/on thing. When could we try having one mounted
overhead? Should prob do that before our "release".

**Comment by bikeoid** [comment]
Been working flawlessly every time I looked at it.   But although the Lunchlink trolley is warming up, I haven't seen it move.  (40 minutes after the scheduled departure).

**Comment by bikeoid** [comment]
Moving now, it was probably a routine maintenance or driver availability issue.

**Comment by greenlinktransit** [comment]
Let's just say that the trolley drivers are a little more casual than the rest.  Not so worried about timing....

**Comment by greenlinktransit** [comment]
@ajhodges I'd like to move one or both phones to the overhead, as well.  @tkenney-gvl or @mblizzard-gvl could you guys help me with that? I'm assuming it just needs a power source, but wasn't sure how that was done.  If you tell me what to plug the phones into, I can go move them myself.

**Comment by greenlinktransit** [comment]
@tkenney-gvl checked out the trolleys yesterday and both phones were in the overhead bins!!! Someone is playing tricks on me.

**Comment by ajhodges** [comment]
Quantum nexus 6es? Maybe Rick got tired of looking at 'em. Good news either way, because they appear to be working just as well! :tada:

**Comment by bikeoid** [comment]
Excellent!   I'd say they're good to go; they're comparable to the previous data.   Out of sight, out of mind!  :+1: 

![trolley_1218](https://cloud.githubusercontent.com/assets/75929/11906572/89224fb4-a59b-11e5-8113-449588f4721c.jpg)

![trolley_1218_imagery](https://cloud.githubusercontent.com/assets/75929/11906579/9641a672-a59b-11e5-851c-f4ec311c0651.jpg)

**Comment by ajhodges** [comment]
Guess we're taking an uber to the well. Trolley is going back and forth
between the well and county square. I got an email from Clemson young
alumni that said we would be able to take a trolley to the game from Nose
Dive so I bit.

**Comment by greenlinktransit** [comment]
Just gave our General Manager a heads up about this. Can't guarantee that it will be corrected this weekend, but we should get this straightened out next week.

**Comment by ajhodges** [comment]
![screenshot_2015-12-18-18-47-58](https://cloud.githubusercontent.com/assets/856738/11909715/ba85c49c-a5b8-11e5-8c68-b25d86cf7d8a.png)
:( it's cold, too :(

**Comment by jeremywight** [comment]
:/

**Comment by ajhodges** [comment]
Redemption. Just got picked up by the trolley from Bon secours. Headed back
to downtown. Happy as a clam :)

**Comment by ajhodges** [comment]
Driver seems to think getting to towers east is more important than
following the route *_*

**Comment by bikeoid** [comment]
Doesn't Towers East come after Bon Secours on our route path?

**Comment by greenlinktransit** [comment]
Sounds like the driver is going rogue. Towers East should technically get cut off when we do the arena deviation. We clearly have some re-training to do on our end
