### ISSUE TITLE
Send out email to everyone letting them know the apps are out of Beta

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#119]
I'm going to write an email and send it out to everyone who signed up for either the iOS or Android app during Beta and let them know the apps are out of beta.

@ajhodges Just give me a :+1:  when you're ready.

**Comment by ajhodges** [comment]
The APK that's pushed right now is in decent shape I think, but is missing the schedule screen. I have a basic schedule screen implemented but really wanted to make it look better before pushing it. And I haven't made the "detailed stop view" which I think we wanted to have done before we removed beta. But I think it'll be good for the initial release if I can just finish up this schedule screen.

**Comment by ajhodges** [comment]
I just uploaded a new APK (will get pushed out in an hour or so) that contains a basic schedule screen. I'd like to test it whenever the trolley is running to make sure it looks good but I'm pretty sure it's about ready.

**Comment by ajhodges** [comment]
There's a couple of glitches with the new UI that I need to fix,
unfortunately. So hold off on pushing it public for now.

**Comment by ajhodges** [comment]
Happy holidays, yall. Just pushed an update to the android client that fixes the UI glitches and improves the schedule UI. It's a pretty good release candidate IMO (this is my :+1: ).

@agautsc I'll let you play the role of QA and test it out and then push it if you think it's ready. It's still missing some stuff but at least the schedule is there.

**Comment by bikeoid** [comment]
Cool schedule on the update!

**Comment by ajhodges** [comment]
Thanks! Android UI stuff has a steep learning curve... been banging my head against the wall a lot. Just pushed another update that will fix issues when the device is rotated.

**Comment by agautsc** [comment]
Are we good to go?

**Comment by ajhodges** [comment]
If you guys are good with it, I am. There are definitely still issues (biggest one being the active route doesn't refresh until the app is restarted) but I'd say it's usable at this point

**Comment by agautsc** [comment]
When I go to the developer console it looks the app is published, but when I check the link in a non-logged in browser I don't see the app.

**Comment by ajhodges** [comment]
Ah, we have to promote a Beta APK to production. Went ahead and did it. Also the play store is pretty slow to update, it takes a couple hours to propagate through.

**Comment by bikeoid** [comment]
Can http://trackthetrolley.com/ be updated to remove beta verbage and link to the apps?   That's a handy name to send people as a starting place to get the apps.

**Comment by bikeoid** [comment]
An announcement from the city - http://www.greenvillesc.gov/civicalerts.aspx?AID=445

**Comment by jeremywight** [comment]
Will do @bikeoid

**Comment by jeremywight** [comment]
Both sites have been updated:

http://trackthetrolley.com
http://yeahthattrolley.com

**Comment by ajhodges** [comment]
![image](https://cloud.githubusercontent.com/assets/856738/12298707/742844ce-b9e1-11e5-937e-4546ce1862da.png)

Nice growth thanks to a post on reddit and on the Downtown Greenville, SC facebook page.

**Comment by agautsc** [comment]
:fireworks: :cake: :fireworks:
