### ISSUE TITLE
Only 1 trolley on Thu night Jan 7

### ISSUE THREAD

**Issue by bikeoid** [codeforgreenville/trolley-tracker#124]
Only 1 trolley was showing for the entire night.   Was the other trolley parked that night?

**Comment by greenlinktransit** [comment]
We have one trolley in service right now -- the other has a major electrical failure, which will put it out of service for about a week.

Do we need to revisit our notification process for these types issues?

**Comment by bikeoid** [comment]
Thanks for the info - I'll adjust the max expected trolleys to 1 until it's back.

Re: notification, it will be handy to keep the text paging service for a while as we're watching it closely.   A quick way to update us on the status when something like this happens is to reply to the notification text.

**Comment by greenlinktransit** [comment]
Has Steve been using the notification system? If not, we might want to re-assign those responsibilities to someone else at Greenlink (either me or the GM).

**Comment by bikeoid** [comment]
Steve was using it in November, but there was no update from last night.    The best notification might go to someone else now that the beacons are working.    

There is not a need for immediate action on the text since any beacon problems now will require more than just a driver intervention.   But just someone who can schedule a maintenance check on the phone, etc.   Maybe that would still be Steve?

**Comment by greenlinktransit** [comment]
Both Steve and James (our GM) know when the trolleys are in and out of service.  Let's keep Steve on there for now but if we run into this problem again, I'll ask James to do it.
