### ISSUE TITLE
Win an Award

### ISSUE THREAD

**Issue by allella** [codeforgreenville/trolley-tracker#133]

**Comment by allella** [comment]
Closing -> http://greenvillesc.gov/CivicAlerts.aspx?AID=476

**Comment by allella** [comment]
Good job folks.

**Comment by ajhodges** [comment]
Adam Grutsch :joy:

**Comment by greenlinktransit** [comment]
@agautsc we picked up a plaque for your award.  Next time you're in the neighborhood, come in a grab it.

**Comment by agautsc** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7897753-125161747_3-s4-v1.png?palette=1&width=246)
