### ISSUE TITLE
Trolley #5 temporary glitch

### ISSUE THREAD

**Issue by bikeoid** [codeforgreenville/trolley-tracker#134]
On Thursday evening, Feb 25, I noticed that only 1 trolley was showing.   I happened to be downtown that night and noticed that both trolleys were running.   Our trolley 6 was working while trolley 5 was invisible.    It corrected itself that night after the route ended and hasn't happened again, so I hadn't written it up until now.

Is there anything related in the Beacon device logs that might give any hint?

**Comment by ajhodges** [comment]
I checked the exception logs and there haven't been any (unhandled) on our
latest release of the agent. I don't persist any other logs.. Do you have
historic data? Maybe we could take a look at the data the server received
and see what the gaps look like? Did trolley 5 start off offline or did it
have an outage? How long was it down, what part of the route was it on when
it went down and came up, etc.

All that might be more trouble than its worth if this is an isolated event
though. Trying to think of other ways to debug this in the future. I could
do some local logging for the agent and have it upload the logs to the
server periodically? But that might be overkill and I'm kind of in a "ain't
broke don't fix it" mindset re: agent at the moment. Would hate to
introduce any other bugs.

**Comment by bikeoid** [comment]
Trolley 5 had run earlier that day, but was off for the entire time of the route - 6 to 11.   It was as though it failed to come online during that one time the trolley was started for the route.   It had come back on overnight, but I didn't check what time it first came back on.

For now, I agree; it's not a serious problem but just something to think about if it happens again.

**Comment by ajhodges** [comment]
So that sounds to me like an issue with the device power on/off mechanism. Maybe the trolley had been turned off/back on quickly. I have a feeling there are some edge cases there. :pray: hope this is isolated. Good to have documented this event, though!

**Comment by tkenney-gvl** [comment]
I'll head down to the maintenance shop either tomorrow or Friday before the weekend run to verify that all the settings are right and that it's operating the way it's supposed to and get back to you. Thanks for the catch!
