### ISSUE TITLE
Officer Jacobs Fundraiser

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#135]
Is there a way the trolley and trolley tracker can help get folks to this event?

https://www.eventbrite.com/e/oyster-roast-fundraiser-for-officer-jacobs-tickets-23840413318

**Comment by greenlinktransit** [comment]
I hate to be a debbie-downer, especially considering the circumstances, but we recently learned from the feds that we can no longer run the trolley (or any other vehicle for that matter) on "special" routes.  That means no more Fall for Greenville, Boo In the Zoo, etc.
