### ISSUE TITLE
Baseball game schedules

### ISSUE THREAD

**Issue by bikeoid** [codeforgreenville/trolley-tracker#138]
What is the trolley schedule during a home baseball game?    Last night's schedule might have covered 

1.  The Swamp Rabbits game at The Well
2.  Main Street
3.  Baseball shuttle

But the actual path by both trolleys was just the baseball game shuttle between Fluor Field and the county square parking lot.     How should the schedule apply when there is a home Greenville Drive game?

**Comment by greenlinktransit** [comment]
Do you have a map of the path that the trolleys took last night???  Typically on baseball games we have one trolley go back and forth between County Sq and Fluor Field while the other Trolley does its usual Main Street Route.  

We will not be servicing BSWA any more due to a lack of ridership to and from that stop.

**Comment by bikeoid** [comment]
![ballshuttle](https://cloud.githubusercontent.com/assets/75929/14383520/a9ece1b2-fd63-11e5-9242-a26a81fa019e.jpg)

Both trolley paths are shown from 6:00 to 11:00pm - colors for Trolley 5 is magenta, Trolley 6 is cyan

**Comment by ajhodges** [comment]
This is the behavior I saw from the trolleys during baseball games last
year as well - they both ran to and from county square with no trolleys
running main street.

**Comment by greenlinktransit** [comment]
Apparently we had so many passengers requesting County Square to Fluor Field service on Opening Day that we used both trolleys to run in between the two areas.  One game days in the future we will run one trolley between County Square and Fluor Field, and the other will service Main Street (w/ the Heritage Green deviation).

**Comment by bikeoid** [comment]
That makes sense to have both trolleys for shuttle at peak times before and after the game.   I'll keep the standard routes listed for game days.
