### ISSUE TITLE
Add pokestops to the trolley map

### ISSUE THREAD

**Issue by ajhodges** [codeforgreenville/trolley-tracker#150]
That's one way to increase the user count ;) could start a whole new wave of poketrolleying!

**Comment by mblizzard-gvl** [comment]
I spoke with our Public Information team.  Because it is city branded, they would rather not have this added to the map.  Their view is to provide useful information for everyone.  if you are not a player, then the map would become cluttered.

**Comment by ajhodges** [comment]
Oh, honestly this was mostly a joke :) but I'm glad to hear an official response on it. Thank you!
