### ISSUE TITLE
Extra Shop Showing in App?

### ISSUE THREAD

**Issue by jeremywight** [codeforgreenville/trolley-tracker#158]
From in App Feedback:

> On the TrolleyTracker, it says it stops on corner of Cleveland and University Ridge and it does not. No sign, no stop according to driver. Loved the 30 minute loop.

**Comment by bikeoid** [comment]
Extra stop now removed - it was left in from  an earlier version.

**Comment by jeremywight** [comment]
Great to know. I'll let the user know!
