### ISSUE TITLE
Pre-Release Marketing Site Feedback

### ISSUE THREAD

**Issue by jeremywight** [codeforgreenville/trolley-tracker#34]
http://trackthetrolley.com/2/

Work in progress, but thoughts on the overall concept-direction?

@agautsc

**Comment by ajhodges** [comment]
I like the background video/design but I think it's a little too shaky. I think you might be able to stabilize the video digitally without it looking awful. And I don't really like how the scrolling is hijacked to make it 'smoother' or whatever.

But other than that I think it will look great once the content is filled in!

**Comment by jeremywight** [comment]
Good feedback. Thanks Adam
