### ISSUE TITLE
Haves and Needs and Things In Betweens 

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#36]
I'm talking with some folks this week about design-y type things and that got me trying to wrap my brain around all the things that are being worked on, who is working on them, what is finished and where help is needed. I'm sure that @jeremywight (who, until yesterday, I would have bet my life last name was Wright. I was wrong ((Sorry Jeremy)) Take note folks there is no 'R' in his surname) and the folks working on things have good grasp of each project, but I'm not 100% what I should be asking folks for. So, I put this together. 

I'm sure I'm missing parts or mis-assigning folks so please feel free to edit to correct. The thing that would be helpful for me is if you're working on particular project and need help with something then edit this doc with a bulleted list of needs and nice to haves. If it's help with design or copywriting or photography or iconography or programming or whatever drop it in and we'll see if we can hunt down help to make this happen. 

# Web app
## Lead
@dacohenii and @Linktheoriginal
## What we have: 
https://github.com/dacohenii/trolley-tracker-web/tree/master/trolley
## What would be nice:

# iOS
## Lead
@austin9350
## What we have:
https://github.com/codeforgreenville/trolley-tracker-ios-client
## What would be nice:

# Android 
## Lead
@ajhodges
## What we have:
Nothing ATM
## What we need:
A hybrid-app that nicely wraps the trolley-tracker-web code.
## What would be nice:
A full-fledged native app (which I can look in to doing, but I'm not super comfortable with UI stuff)

# Marketing site
## What we have:
http://trackthetrolley.com/2/
## What would be nice:

# Android Beacon Agent 
## Lead
@ajhodges
## What we have:
https://github.com/codeforgreenville/trolley-tracker-agent
## What we need:
*More info on whichever device the trolley will go on. Can we use the RouteMatch tablets? Does the device power on/off fully when the trolley is turned on/off? If no, does it go in a sleep state? How else will we be able to determine if a trolley is 'active' or not? Do we signal when a trolley turns on, or do we just adjust the API to only return trolley location data if the data is <15mins old?
*Also need a way of deploying the app/updates. Google Play doesn't let you have private apps unless you have a Google Apps account, but it does let you create invite-only 'beta' access. We can release the Android Beacon as a 'beta' so only the trolley Google accounts can download/get updates for our app. Updates on the devices need to be set to automatic.
## What would be nice:
*A better UI/logging for debugging
*Remote administration tools (I use Cerberus for my personal phone, but maybe we can find something more intended for remote device administration rather than security)

# Trolley Tracker API
## Lead:
@thedanfields
## What we have:
https://github.com/codeforgreenville/trolley-tracker-api
## What would be nice:

# Windows
## Lead:
@thedanfields

**Comment by jeremywight** [comment]
Haha. Don’t sweat it Adam, everyone gets my name wrong :)

Great work on the doc. We’ll see what people input.

Jeremy

**Comment by Linktheoriginal** [comment]
I was looking into what it takes to do a quick app that loads the map from a site and came across this for Android: http://stackoverflow.com/questions/8101933/how-to-wrap-a-website-in-a-phone-app

However, from the comments it looks like apps like this are rarely/never accepted without some sort of feature-add.

API need: get info about all trolleys at once.
API want: route data storage.

**Comment by ajhodges** [comment]
@Linktheoriginal, I think I am going to volunteer to take ownership of making the hybrid Android app. Let me know when you think the map is 'ready' and I will see what I can whip up.
