### ISSUE TITLE
Design and Final Planning

### ISSUE THREAD

**Issue by jeremywight** [codeforgreenville/trolley-tracker#47]
Just talked with our contacts over at Erwin Penland, they anticipate having a design to us next week (8/18). I think if we can get that design integrated in to the front end prior to a meetup on 8/25, we could do some QA final tweaking and potentially be ready to submit to the app store for a planned mid-Sept launch.

Thoughts?

**Comment by Linktheoriginal** [comment]
It sounds like the design is for the iOS app?  I'd like to take a look as well for anything to possibly incorporate into the web app.

**Comment by jeremywight** [comment]
Yes, both iOS and Webapp, with a consistent styling on the Marketing page.

**Comment by jeremywight** [comment]
@Linktheoriginal Where do we want to host the web app post-launch? Is that going to be on the Azure server or should we move? Just want to make sure we are ready. You've probably thought about it I may have just missed it.

**Comment by Linktheoriginal** [comment]
I'm planning on supporting what I have right now on webfactional - we've discussed moving it, and what would be involved there, but I think that decision needs to wait depending on the amount of load we see.  Also, to my knowledge, the current production is walling info systems, not the azure servers (depending on what you mean).

**Comment by jeremywight** [comment]
Thanks for the insight. I meant walling server. Maybe a we could run
loader.io against it to see what happens, not sure if we would be able to
pass location data though to it to simulate.

**Comment by bikeoid** [comment]
If we have one of our domains that we can give to Greenlink to post as a QR code decal on signs, that domain could redirect to webfactional.   It could stay there or change later if we wish.

**Comment by agautsc** [comment]
EP design comps https://drive.google.com/drive/folders/0B1Wxj_5D6dLNfnFEeXo3a3pFVl9VVmxmWWpaNElCaXJrUXhxNi0ycVdOb3Y2SzRrWExFRTA
