### ISSUE TITLE
Agent Install Update

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#48]
The second trolley has the agent installed. I have changed the ID for that trolley to '6' but left all other items the same. 

@ajhodges I don't see the coordinates running down the screen, but everything else seems to be in working order. Hoping that's a switch you can turn on your side.

The '5' trolley is still in internet limbo. Rick is working on it.

**Comment by bikeoid** [comment]
I created a Trolley #6 (current Database ID = 1)
