### ISSUE TITLE
Limo tracker

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#51]
Some folks from OW are taking a limo up to Spartanburg on Thursday to attend the Iron Yard Ventures Demo Day. http://www.eventbrite.com/e/iron-yard-ventures-2015-demo-day-tickets-17399363966?aff=limo

Would it be possible install the beacon on a phone and slap that feed on a map just to test this bad boy on the road?

CC:
@ajhodges 
@bikeoid 
@dacohenii 
@Linktheoriginal

**Comment by ajhodges** [comment]
Absolutely possible on my end... just install the app on your phone and edit the settings to point it to the new API

**Comment by bikeoid** [comment]
Is the app in the Google Play Store, and what is the name?

**Comment by ajhodges** [comment]
The app is in the Play Store as a beta and I can whitelist accounts to have access (I did not want to make it public since it is only used by the trolley), just send me the gmail account you use on your phone.

**Comment by agautsc** [comment]
agautsc@gmail.com

**Comment by bikeoid** [comment]
jazzerbyte@gmail.com

**Comment by ajhodges** [comment]
Okay! This should work with your account: https://play.google.com/apps/testing/com.codeforgvl.trolleytracker

It's not the completely latest version but it should work well enough to test the new API. Thanks!

**Comment by agautsc** [comment]
It says my account isn't white listed.

**Comment by bikeoid** [comment]
I get that also ... "A beta version of this app hasn't been published yet or isn't available for this account."

**Comment by ajhodges** [comment]
Join the google group I just invited you guys to and then try again.

**Comment by agautsc** [comment]
Installed. Made my phone Trolley number 8 Tried to 'Create a Trolley' by going here http://yeahthattrolley.azurewebsites.net/Trolleys I don't think I have the proper permissions to do so.

**Comment by bikeoid** [comment]
Re:  proper permissions to do so -

Sign in with the account username  ManageTrolley@yeahthattrolley.com , 
pw  ManageTrolley7!
 
   That will let you manage the trolleys etc.   I'm keeping that public account until it moves to the new server.

**Comment by agautsc** [comment]
Thank ya Mike. Sorry, I should have read the API documentation. It was there all along.

**Comment by bikeoid** [comment]
FYI - I think I need to update the new vehicle API to match the previous API.   I didn't know if the beacon was the same or had been updated.    Tracking down the parameters now....

**Comment by bikeoid** [comment]
API updated for backward compatibility now, and should work.   The 'Trolley ID' number in the Beacon setting now refers to the Number in the trolley Number (999 for example in our trolley list).

**Comment by agautsc** [comment]
That got things moving.
