### ISSUE TITLE
Trolley #5 Online

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#55]
I sat next to Hodges on the trolley #5 today as he updated a bunch of software on the tablet including the beacon app. Now, both trolleys should be working.

Hopefully, the trolleys will be running for the Drive game tomorrow and we'll have live data to show off for the meeting.

**Comment by ajhodges** [comment]
:+1:

**Comment by ajhodges** [comment]
Number 5 is alive

**Comment by jeremywight** [comment]
Aww yeah... Giddy up!!!
