### ISSUE TITLE
Baseball Game Tonight

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#58]
Talked with Kathy today and she said there is a baseball game tonight and she is going to send an email to Greenlink to remind them to turn on the tablets. 

Hopefully we can see some action tonight.

**Comment by jeremywight** [comment]
+1

**Comment by bikeoid** [comment]
Re: Baseball scheduling ... does the baseball game shuttle supersede a normal route for that evening?  What time does the ball game shuttle start relative to game start?   

It would be great if there was some way to have the tablets automatically power up.

**Comment by agautsc** [comment]
Re: Schedule baseball / normal schedule. I believe that one trolley runs the baseball loop and one runs the regular route.
