### ISSUE TITLE
Double Trolley All The Way

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#62]
Check the map!

**Comment by ajhodges** [comment]
WHOAAAAAAAA DOUBLE TROLLEYYYYYYYY ITS SO BEAUTIFULLLLLL! OMG

**Comment by agautsc** [comment]
Well. 452pm they are offline.

**Comment by ajhodges** [comment]
Only one online at 6:46..

**Comment by ajhodges** [comment]
Now none..
