### ISSUE TITLE
Meet with the Trolley Drivers

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#66]
Greenlink is organizing a meeting with CfG and the trolley drivers. The hope is we can tell a little bit of the story of what it took to make this happen and we can give them some tips and tricks to make sure the trolley beacon agent stays up and connected. 

Any thoughts on this are welcomed and anyone who can and wants to attend the meeting is welcomed as well. The meeting time and date is still be figured out.

**Comment by jeremywight** [comment]
I’m out starting Thur 9/3 - Thur 9/10. So unless we did tomorrow morning at 830 or 9am I’m out until I return, but I do think we need to determine the root cause of our issue(s) and see them rise to a level of service that would be worthy of marketing.

**Comment by bikeoid** [comment]
Any feedback if they are interested in a meeting, or general idea of when?

**Comment by agautsc** [comment]
No word, but things weren't working great last night or today during lunch, so I'm imagine we need to have some type of meeting.

**Comment by agautsc** [comment]
Grant from Greenlink met with the drivers a couple of times and gave them lessons on the tablet. It seemed one issue was some of them thought that the tablet was on because the saw the battery charging sign. Everyone should know the basics now.
