### ISSUE TITLE
Had a separate API that returned test data 24/7 (for developing clients)

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#68]
https://codeforgvl.imaginethat.io/trolleytracker/i/5328

**Comment by ajhodges** [comment]
There might be something like this already. It would be cool if we also had an admin panel to test different scenarios, aka single trolley multiple routes, single route multiple trolleys, signal a route 'change', etc. I know we have the admin panel right now but I was thinking more along the lines of dummy data, so we aren't testing against production. As of right now I have to wait until the trolleys are running to test (and they aren't running reliably haha)

**Comment by bikeoid** [comment]
I still have the Azure instance available ; I don't have anything else planned for it at the moment so I can post the latest program there and you can freely configure it.

**Comment by bikeoid** [comment]
It's up now - same login credentials as the real site -   http://yeahthattrolley.azurewebsites.net/   Just 1 simulated trolley for now.

 I need to visually distinguish it from the real site, and have the simulated trolleys somehow selectable, but it's a start.

**Comment by bikeoid** [comment]
Shockingly, I see 2 real trolleys warming up in the real trolley barn!

**Comment by ajhodges** [comment]
@bikeoid hate to nag, I don't see the simulated trolley anymore. Does it run on a schedule or is it 24/7? It's been really helpful for my testing :)

**Comment by bikeoid** [comment]
No problem - I run the simulator on another computer, and it was just upgraded to Windows 10 and the upgrade removed it from the autostart list!   Should be running now.

**Comment by ajhodges** [comment]
Thanks!!

**Comment by ajhodges** [comment]
One last request - is it a pain for you to update the old API? I updated the Android client to pull the schedule and it can't. You don't have to keep it bleeding edge or anything, just whenever it's easy :)

**Comment by bikeoid** [comment]
It should be no problem - by old API: do you mean the dev server at http://yeahthattrolley.azurewebsites.net/ ?    Both servers are running the same level of software, and only the schedules are different for testing.   The production server at http://api.yeahthattrolley.com/ should also be working.

**Comment by ajhodges** [comment]
Weird, I must have another issue. Code was throwing an error when loading
the schedule from the azurewebsites.net version, but not yeahthattrolley.com.
Didn't look in to it and assumed they were running different versions. Time
to dig!

**Comment by ajhodges** [comment]
I can't seem to get a response from http://yeahthattrolley.azurewebsites.net/api/v1/RouteSchedules

**Comment by bikeoid** [comment]
Sorry about that - I need to run the test suite on that server also when I make changes.   I've corrected the code on that server so the schedule will work now.
