### ISSUE TITLE
Recap from the weekend

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#73]
I'd like to send Greenlink a recap from weekend. This is what I've got. Let me know if I'm off.

* Thursday - Neither worked all day
* Friday time - neither worked during lunch at all
* Friday night - Both worked all night
* Saturday - Trolley 5 ran most of the day (it seems like it was left on from Friday night)
* Sunday - Trolley 5 ran all day as well. 

In the past, Trolley 5 was our trouble trolley. Now, it seems to be the other way around.

Am I missing something?

**Comment by ajhodges** [comment]
Seems to align with my experiences. I'm wondering if the issues with
trolley 6 are related to both tablets being left on Friday night.

**Comment by agautsc** [comment]
Sent to Greenlink

**Comment by jeremywight** [comment]
Did they give any reply?
