### ISSUE TITLE
Push for Next Thursday

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#74]
I'm going to be speaking at Technically a Coffee briefly on Thursday of next week to talk about the Trolley Tracker. I don't know exactly what I'm going to say because we haven't gone longer than a day with both trolleys running the whole time. 

That being said, I'd still like to give folks who are there the chance to download the apps and be testers if nothing else. I think there should be some warning going on with the app letting folks it's still in the test phase or something like that as well. 

Is this doable? Do we need to meet for anything before then? 

Let me know.

Also, anyone who can attend that Technically a Coffee please do come out. I'd love to spotlight anyone who worked on the project.  http://sched.co/48Pt

Double also, there are still spots on the trolley for the the Thursday brewery tour if folks are around and interested. http://sched.co/482x 

Wanted to add @bikeoid @austin9350 @Linktheoriginal into this message and see if y'all have any thoughts.

**Comment by ajhodges** [comment]
How do you feel about using the open beta opt-in link for the Android client? (https://play.google.com/apps/testing/com.codeforgvl.trolleytrackerclient) I'm hesitant to push a live version because it opens up reviews and if the tablets aren't running consistently and the schedules aren't 100% nailed down (managed by Greenlink) then the app will be prone to negative reviews. That takes care of the warning too, by making it opt-in.

Your call though.

**Comment by agautsc** [comment]
I think the Beta is the right way to go. Evan had some issues signing up through that process earlier, but he was able to install it today. 

I think it is worth getting a couple of people to test the Beta signup process so we can explain that properly to people.

**Comment by ajhodges** [comment]
I think the confusion stems from having different Google accounts and being
signed in as one account during the opt-in and another on the play store.
Can't believe Google hasn't streamlined that more.

**Comment by agautsc** [comment]
Jim's feedback on signing up through the Beta process "Installed the app. The only thing that was mildly confusing was that when I hit the "Become a Tester" button on the first page I was expecting that to do the actual installation. When I got to the next page and it provided details about how to install it took me reading the text to realize I'd only accepted to be a tester and that I still needed to install the app as a second step." Good note, we can try to do some explaining to folks both in person in and in copy to help with that.

**Comment by jeremywight** [comment]
I’ll see if I can make it to the meeting on Thursday. Where can I see this beta sign up process?

**Comment by agautsc** [comment]
https://play.google.com/apps/testing/com.codeforgvl.trolleytrackerclient You need to be signed in to Google to see the signup process.

**Comment by jeremywight** [comment]
Got it. I already signed up for this before... I think that the process was
fairly straight forward. Are there any objections to just having a small
FAQ on the marketing site on how to signup for Beta access?
