### ISSUE TITLE
Thursday

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#76]
Did anyone check the trolleys last night? When I checked one of the two trolleys was running.

**Comment by ajhodges** [comment]
Yep I only saw trolley 5. It's been about a week since 6 has shown up. Hope
it's just unplugged

**Comment by agautsc** [comment]
From Kathy: The other trolley is in he shop for transmission issues. We're meeting with drivers at 10:30 so Lunchlink should be working as well as tonight.

**Comment by ajhodges** [comment]
I see trolley 5 on lunchlink

**Comment by ajhodges** [comment]
Trolley 5 ran all night, even found it a couple times. Appears the tablet
was left on. Still running.
