### ISSUE TITLE
Thursday 10:30 No Active Routes

### ISSUE THREAD

**Issue by Linktheoriginal** [codeforgreenville/trolley-tracker#93]
Checked in on the trolley tonight, and there's no active routes being returned via the API (so the schedule is showing on the webapp, but the trolley is tracking behind it, without a route).  There's a current schedule being returned for this time - ShortMain County Sq.  Not sure what's up with the API - could it be a time zone issue?
![1030thursday](https://cloud.githubusercontent.com/assets/574842/10238391/23e79f64-688d-11e5-8031-2ac6006bca2b.png)

**Comment by bikeoid** [comment]
It turns out that from my preliminary analysis, the clock on the server is set about 12 hours behind.  I'm not sure why the Windows Time Server didn't correct it, but I should learn more about it tomorrow when Joe takes a look.

**Comment by bikeoid** [comment]
The server time has been corrected, and the server is also now set to sync to Internet time.   Just in time for LunchLink!
