### ISSUE TITLE
Stops not showing

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#94]
The route is up but I'm not seeing stops on either the web or the app.

**Comment by Linktheoriginal** [comment]
The API is not returning stops: http://tracker.wallinginfosystems.com/api/v1/Routes/3
![nostops](https://cloud.githubusercontent.com/assets/574842/10250878/75a1aa20-68fb-11e5-9efc-1abc5cf5c86c.png)

**Comment by bikeoid** [comment]
This route is designated as "Flag stops only" since there are no trolley stop signs hung on the northbound side of the street.    OR, is it better to show the stops where there are signs?

**Comment by agautsc** [comment]
According to Kathy riders are suppose to use the stops on the lunch route too.

**Comment by bikeoid** [comment]
Change to use existing stops for this route.
