### ISSUE TITLE
Add Fall for Greenville Routes

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#95]
More discussion here https://github.com/codeforgreenville/trolley-tracker/issues/84 and some files https://drive.google.com/drive/folders/0B1Wxj_5D6dLNfnFEeXo3a3pFVl9VVmxmWWpaNElCaXJrUXhxNi0ycVdOb3Y2SzRrWExFRTA

**Comment by bikeoid** [comment]
Add routes and updated schedule

**Comment by greenlinktransit** [comment]
[JANUARY 2016 BSWA Schedule.pdf](https://github.com/codeforgreenville/trolley-tracker/files/68954/JANUARY.2016.BSWA.Schedule.pdf)
For your eyes only: Attached is the schedule for the Well in January.
